name: app-check

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Using
        run: |
          make setup
          make start
      - name: Run tests
        run: make test
      - name: Run linter
        run: make lint
